global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # CodeGuardian main application
  - job_name: "codeguardian"
    static_configs:
      - targets: ["codeguardian:8000"]
    metrics_path: /metrics
    scrape_interval: 10s

  # Web UI service
  - job_name: "codeguardian-web"
    static_configs:
      - targets: ["web-ui:5000"]
    metrics_path: /metrics
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  # Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # Nginx metrics
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: /nginx_status
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
