# Fusion Model Configuration
# Phase 3.2 Enhanced Training Configuration

model_name: "xgb_fusion"
version: "3.2.0"

# Data Configuration
data:
  fused_dir: "datasets/fused"
  splits:
    train: "train_with_static.jsonl"
    val: "val_with_static.jsonl"
    test: "test_with_static.jsonl"
  
  # Required features from fusion dataset
  required_features:
    # Static model outputs
    - static_prob
    - static_confidence
    
    # CodeBERT outputs
    - codebert_prob
    - codebert_logit
    
    # GraphCodeBERT outputs
    - graphcodebert_prob
    - graphcodebert_logit
  
  # Optional embedding features (aggregated stats)
  embedding_features:
    enabled: true
    aggregations:
      - mean
      - max
      - std
    prefix: "embedding_"
  
  # Metadata features
  metadata_features:
    - language
    - has_vulnerabilities
    - vulnerability_count
    - severity_score
  
  target_column: "label"
  id_column: "id"

# Feature Engineering
feature_engineering:
  # Interaction features
  create_interactions: true
  interactions:
    - ["static_prob", "codebert_prob"]
    - ["static_prob", "graphcodebert_prob"]
    - ["codebert_prob", "graphcodebert_prob"]
    - ["static_confidence", "codebert_prob"]
  
  # Ratio features
  create_ratios: true
  ratios:
    - ["static_prob", "codebert_prob", "static_codebert_ratio"]
    - ["graphcodebert_prob", "codebert_prob", "graph_codebert_ratio"]
  
  # Ensemble features
  create_ensemble_features: true
  ensemble:
    mean_prob: ["static_prob", "codebert_prob", "graphcodebert_prob"]
    max_prob: ["static_prob", "codebert_prob", "graphcodebert_prob"]
    min_prob: ["static_prob", "codebert_prob", "graphcodebert_prob"]

# Preprocessing
preprocessing:
  impute_strategy: "median"
  scale_features: false
  handle_categorical: "onehot"
  max_categories: 50
  clip_probabilities: true  # Clip to [0, 1]

# Model Hyperparameters (defaults - favor shallow trees)
model:
  # Core parameters
  n_estimators: 300
  max_depth: 5
  learning_rate: 0.1
  
  # Regularization
  gamma: 0.5
  min_child_weight: 5
  subsample: 0.7
  colsample_bytree: 0.7
  colsample_bylevel: 0.7
  
  # Additional
  tree_method: "hist"
  eval_metric: ["aucpr", "auc"]
  early_stopping_rounds: 30
  
  # Class imbalance
  scale_pos_weight: null  # auto-calculated
  
  # Random seed
  random_state: 42
  
  # Other
  n_jobs: -1
  verbosity: 1

# Hyperparameter Tuning
tuning:
  enabled: false
  n_trials: 30
  timeout: null
  
  # Search space (shallower trees for fusion)
  search_space:
    n_estimators:
      type: "int"
      low: 50
      high: 500
      step: 50
    max_depth:
      type: "int"
      low: 3
      high: 8
    learning_rate:
      type: "float"
      low: 0.01
      high: 0.3
      log: true
    subsample:
      type: "float"
      low: 0.6
      high: 1.0
    colsample_bytree:
      type: "float"
      low: 0.5
      high: 1.0
    gamma:
      type: "float"
      low: 0.0
      high: 2.0
    min_child_weight:
      type: "int"
      low: 3
      high: 10
  
  direction: "maximize"
  metric: "pr_auc"
  cv_folds: 5

# Cross-Validation
cross_validation:
  enabled: true
  n_folds: 5
  stratified: true
  save_fold_predictions: true

# Ensembling
ensemble:
  enabled: false
  n_models: 3
  method: "averaging"  # averaging or stacking
  different_seeds: true

# Class Imbalance
imbalance:
  strategy: "scale_pos_weight"
  threshold_ratio: 1.5
  
  smote:
    k_neighbors: 5
    sampling_strategy: "auto"

# Calibration
calibration:
  enabled: true
  method: "isotonic"
  cv_folds: 5

# Explainability
explainability:
  enabled: true
  save_plots: true
  save_samples: true
  n_samples: 500
  
  # Feature importance analysis
  analyze_subsystem_contribution: true  # static vs codebert vs graph
  
  shap:
    check_additivity: false
    approximate: true
    max_evals: 1000

# Evaluation
evaluation:
  metrics:
    - roc_auc
    - pr_auc
    - f1
    - precision
    - recall
    - accuracy
    - brier_score
  
  optimize_threshold: true
  threshold_metric: "f1"
  
  save_confusion_matrix: true
  save_roc_curve: true
  save_pr_curve: true
  save_reliability_diagram: true
  
  # Compare with baseline
  compare_with_best_single: true  # Compare with best single model

# Output Paths
output:
  models_dir: "models/fusion"
  metrics_dir: "metrics"
  plots_dir: "plots/fusion"
  shap_dir: "shap/fusion"
  logs_dir: "logs/fusion"
  predictions_dir: "datasets/predictions"
  
  model_filename: "xgb_fusion_v{timestamp}.joblib"
  metadata_filename: "metadata_xgb_fusion_v{timestamp}.yaml"
  metrics_filename: "fusion_eval_{split}.json"

# Logging
logging:
  level: "INFO"
  save_to_file: true
  log_filename: "training_xgb_fusion_{timestamp}.log"

# Reproducibility
reproducibility:
  seed: 42
  deterministic: true
  save_git_commit: true
  save_environment: true
