name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck jq composer nodejs npm golang-go
          # Install gosec (may require Go 1.20+)
          /bin/bash -lc "GO111MODULE=on go install github.com/securego/gosec/v2/cmd/gosec@latest"
          # Install phpcs via composer
          /bin/bash -lc "composer global require --no-interaction squizlabs/php_codesniffer"
          # Install eslint and security plugin
          sudo npm install -g eslint eslint-plugin-security
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Run analyzers
        run: |
          python src/engine/analyzers/run_all_analyzers.py demos/ analysis_results_ci.json
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: static-analysis-results
          path: analysis_results_ci.json
